LibraryManagementApp/Models/BookIssue.cs
using LibraryManagementApp.Enums;
using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel.DataAnnotations;
using LibraryManagementApp.Data.Base;

namespace LibraryManagementApp.Models
{
    public class BookIssue : IEntityBase
    {
        [Key]
        public int Id { get; set; }
        public string? BorrowersName { get; set; }
        public string? BorrowingLibrariansName { get; set; }
        public string? ReturningLibrariansName { get; set; }
        public DateTime TimeBorrowed { get; set; }
        public DateTime TimeReturned { get; set; }
        public DateTime DueDate { get; set; }
        public BookStatus bookStatus { get; set; }
        public BookReturnStatus bookReturnStatus { get; set; }

        //Relationships
        public int BookInstanceId { get; set; }
        [ForeignKey("BookInstanceId")]
        public BookInstance? BookInstance { get; set; }

        //public int CardId { get; set; }
        //public LibraryCard? Card { get; set; }
    }
}

LibraryManagementApp/Controllers/BookIssueController.cs
using LibraryManagementApp.Data.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using LibraryManagementApp.Models;
using LibraryManagementApp.Enums;
using LibraryManagementApp.Data.ViewModels;
using Microsoft.AspNetCore.Mvc.Rendering;
using LibraryManagementApp.Data.Static;
using System.Net;
using Microsoft.IdentityModel.Tokens;
using static System.Runtime.InteropServices.JavaScript.JSType;

namespace LibraryManagementApp.Controllers
{
    [Authorize(Roles = UserRoles.Admin + "," + UserRoles.Librarian)]
    public class BookIssueController : Controller
    {
        private readonly IBookIssueService _service;

        public BookIssueController(IBookIssueService service)
        {
            _service = service;
        }

        public async Task<IActionResult> Index(int? i, string? searchString)
        {
            if (i < 1) i = 1;

            var allIssues = await _service.GetAllAsync(n => n.BookInstance);

            if (string.IsNullOrWhiteSpace(searchString))
            {
                var allBookIssues = await PaginatedList<BookIssue>.CreateAsync(allIssues, i ?? 1, 8);
                return View(allBookIssues);
            }

            var filteredData = allIssues.Where(n => "NotYetReturned".Equals(searchString)
                ? n.bookReturnStatus.Equals(Enum.Parse<BookReturnStatus>(searchString))
                : string.Equals(n.BorrowersName, searchString, StringComparison.CurrentCultureIgnoreCase));

            var filterPagedData = await PaginatedList<BookIssue>.CreateAsync(filteredData, i ?? 1, 8);
            ViewBag.searcheditem = searchString;

            //int totalPages = PageLength.Length;
            //if (i > totalPages) i = totalPages;

            return View(filterPagedData);
        }

        //Create
        public IActionResult Create() 
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Create(BookIssueVM bookIssueVM)
        {
            if (!ModelState.IsValid) { return View(bookIssueVM); }

            //await _service.AddAsync(bookIssue);
            await _service.AddNewBookIssueAsync(bookIssueVM);
            return RedirectToAction(nameof(Index));
        }

        //Edit
        public async Task<IActionResult> Edit(int id)
        {
            var bookIssueDetails = await _service.GetByIdAsync(id, n => n.BookInstance);
            if (bookIssueDetails == null)
                return NotFound();

            var response = new EditBookIssueVM()
            {
                BorrowersName = bookIssueDetails.BorrowersName,
                BorrowingLibrariansName = bookIssueDetails.BorrowingLibrariansName,
                ReturningLibrariansName = bookIssueDetails.ReturningLibrariansName,
                TimeBorrowed = bookIssueDetails.TimeBorrowed,
                TimeReturned = bookIssueDetails.TimeReturned,
                DueDate = bookIssueDetails.DueDate,
                bookStatus = bookIssueDetails.bookStatus,
                bookReturnStatus = bookIssueDetails.bookReturnStatus,
                BookInstanceId = bookIssueDetails.BookInstanceId
            };

            var bookIssueDropdownsData = await _service.GetBookIssueDropdownsValues();
            ViewBag.BookInstances = new SelectList(bookIssueDropdownsData.BookInstances, "Id", "IsbnNumber");

            var date = bookIssueDetails.TimeBorrowed;
            ViewBag.TimeBorrowedDate = date;

            return View(response);
        }
        [HttpPost]
        public async Task<IActionResult> Edit(int id, EditBookIssueVM editBookIssueVM)
        {
            if (id != editBookIssueVM.Id) return View("Not Found");

            if (ModelState.IsValid)
            {
                //await _service.UpdateAsync(bookIssue.Id, bookIssue);
                await _service.UpdateBookIssueAsync(editBookIssueVM);
                return RedirectToAction(nameof(Index));
            }

            var bookIssueDropdownsData = await _service.GetBookIssueDropdownsValues();
            ViewBag.BookInstances = new SelectList(bookIssueDropdownsData.BookInstances, "Id", "IsbnNumber");

            var date = editBookIssueVM.TimeBorrowed;
            ViewBag.TimeBorrowedDate = date;

            return View(editBookIssueVM);
        }

        //Details
        //[AllowAnonymous]
        [Authorize]
        public async Task<IActionResult> Details(int id)
        {
            var bookIssueDetails = await _service.GetByIdAsync(id, n => n.BookInstance);
            if (bookIssueDetails == null)
                return NotFound();
            return View(bookIssueDetails);
        }

        //Delete
        public async Task<IActionResult> Delete(int id)
        {
            var bookIssueDetails = await _service.GetByIdAsync(id);
            if (bookIssueDetails == null) return View("Not Found");
            return View(bookIssueDetails);
        }
        [HttpPost, ActionName("Delete")]
        public async Task<IActionResult> DeleteConfirmed(int id, BookIssue bookIssue)
        {
            var bookIssueDetails = await _service.GetByIdAsync(id);
            if (bookIssueDetails == null) return View("Not Found");

            await _service.DeleteAsync(id);
            return RedirectToAction(nameof(Index));
        }

        //History
        [AllowAnonymous]
        public async Task<IActionResult> History(int? i, string? searchString)
        {
            string email = User.Identity.Name;
            var bookIssueDetails = await _service.GetAllAsync(n => n.BookInstance);
            var results = bookIssueDetails.Where(n => string.Equals(n.BorrowersName, email, StringComparison.CurrentCultureIgnoreCase)).ToList();

            if (!string.IsNullOrEmpty(searchString))
            {
                var filteredData = results.Where(n => n.bookReturnStatus.Equals(Enum.Parse<BookReturnStatus>(searchString)));

                var filterPagedData = await PaginatedList<BookIssue>.CreateAsync(filteredData, i ?? 1, 8);
                ViewBag.searcheditem = searchString;

                return View(filterPagedData);
            }

            var pagedResults = await PaginatedList<BookIssue>.CreateAsync(results, i ?? 1, 8);

            return View(pagedResults);
        }

        //Dues
        [Authorize]
        public async Task<IActionResult> Dues(int id)
        {
            var bookIssueDetails = await _service.GetByIdAsync(id, n => n.BookInstance);
            if (bookIssueDetails == null)
                return View();

            return View(bookIssueDetails);
        }

        //Return A Book
        public async Task<IActionResult> ReturnBook(int id)
        {
            var bookIssueDetails = await _service.GetByIdAsync(id, n => n.BookInstance);
            if (bookIssueDetails == null)
                return NotFound();

            var response = new BookIssue()
            {
                ReturningLibrariansName = bookIssueDetails.ReturningLibrariansName,
                TimeReturned = bookIssueDetails.TimeReturned,
                bookReturnStatus = bookIssueDetails.bookReturnStatus,
                BookInstanceId = bookIssueDetails.BookInstanceId,
                BookInstance = bookIssueDetails.BookInstance,
                BorrowersName = bookIssueDetails.BorrowersName
            };

            return View(response);
        }
        [HttpPost]
        public async Task<IActionResult> ReturnBook(int id, BookIssue bookIssue)
        {
            if (id != bookIssue.Id) return View("Not Found");

            var issue = await _service.GetByIdAsync(bookIssue.Id, n => n.BookInstance);

            if (ModelState.IsValid)
            {
                if (bookIssue.bookReturnStatus == BookReturnStatus.NotYetReturned)
                {
                    TempData["Error"] = "The Return Status of a book cannot be set to 'NotYetReturned'. " +
                        "Please specify the current returned state of the book in the Return Status field.";
                    return View(issue);
                }
                await _service.ReturnBookAsync(bookIssue);
                return RedirectToAction(nameof(Index));
            }

            return View(issue);
        }
    }
}

LibraryManagementApp/Views/BookIssue/Create.cshtml
@using LibraryManagementApp.Enums;
@using LibraryManagementApp.Data.ViewModels;
@model BookIssueVM

@{
    ViewData["Title"] = "Issue a Book";
    //var today = DateTime.Now.Date;
    string name = User.Identity.Name;
    var today = DateTime.Now.Date.ToString("yyyy-MM-dd");//Thh:mm
    var low = DateTime.Now.AddDays(1).ToString("yyyy-MM-dd");
    var high = DateTime.Now.AddDays(14).ToString("yyyy-MM-dd");
}

<div class="row text">
    <div class="col-md-8 offset-2">
        <p>
            <h4 class="text-center">Issue a Book</h4>
        </p>
        <div class="row" style="margin: auto; display: flex; justify-content: center;">
            <div class="col" style="max-width: 500px;">
                <div class="card">
                    <div class="card-body">
                        <form asp-action="Create">
                            <div asp-validation-summary="ModelOnly" class="text-danger"></div>

                            <div class="form-group mb-2">
                                <label class="form-label">Book: </label>
                                <input id="searchInput" class="form-control" />
                            </div>
                            <div class="form-group mb-2">
                                <select id="instance" asp-for="BookInstanceId" class="form-control form-select">
                                    <option disabled selected>Choose the Isbn...</option>
                                </select>
                                <span asp-validation-for="BookInstanceId" class="text-danger"></span>
                            </div>
                            <div class="form-group mb-2">
                                <label asp-for="BorrowersName" class="form-label">Email: </label>
                                <input asp-for="BorrowersName" id="borrower" class="form-control" />
                                <span asp-validation-for="BorrowersName" class="text-danger"></span>
                            </div>
                            <div class="row">
                                <div class="col-md-6 form-group mb-2">
                                    <label asp-for="BorrowingLibrariansName" class="form-label">Borrowing Librarian: </label>
                                    <input asp-for="BorrowingLibrariansName" class="form-control" value="@name" />
                                    <span asp-validation-for="BorrowingLibrariansName" class="text-danger"></span>
                                </div>
                                <div class="col-md-6 form-group mb-2">
                                    <label asp-for="bookStatus" class="form-label">Status:</label>
                                    <select asp-for="bookStatus" class="form-control form-select" asp-items="Html.GetEnumSelectList<BookStatus>()"></select>
                                    <span asp-validation-for="bookStatus" class="text-danger"></span>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-6 form-group mb-2">
                                    <label asp-for="TimeBorrowed" class="form-label">Issue Date: </label>
                                    <input asp-for="TimeBorrowed" class="form-control" type="date" value="@today" />
                                    <span asp-validation-for="TimeBorrowed" class="text-danger"></span>
                                </div>
                                <div class="col-md-6 orm-group mb-2">
                                    <label asp-for="DueDate" class="form-label">Due Date: </label>
                                    <input type="date" asp-for="DueDate" min="@low" max="@high" class="form-control" />
                                    <span asp-validation-for="DueDate" class="text-danger"></span>
                                </div>
                            </div>
                            <div class="form-group mt-3">
                                <a class="btn btn-light" asp-action="Index"><i class="bi bi-box-arrow-left"></i> Show All</a>
                                <button type="submit" class="float-end btn btn-outline-success">
                                    Create <i class="bi bi-check2-circle"></i>
                                </button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

@section scripts{
    <script>
        $(document).ready(function () {
            const title = $("#searchInput");
            const instance = $("#instance");
            instance.prop('disabled', true);
            let bookId = 0;
            let name = "";

            $("#searchInput").autocomplete({
                source: function (request, response) {
                    $.ajax({
                        url: "/Book/GetTitle",
                        type: "POST",
                        dataType: "json",
                        data: { term: request.term },
                        success: function (data) {
                            response($.map(data, function (item) {
                                return { label: item.name, value: item.name, id: item.id };
                            }));
                        }
                    });
                },
                minLength: 3,
                select: function (event, ui) {
                    //console.log(ui);
                    bookId = ui.item.id;
                    name = ui.item.label;
                }
            });
            
            $("#searchInput").blur(function () {
                if ($(this).val() == "0") {
                    instance.prop('disabled', true);
                    instance.val("0");
                }
                else {
                    instance.prop('disabled', false);
                    instance.empty();
                    $.ajax({
                        url: "/BookInstance/GetInstance?bookId=" + bookId,
                        method: "get",
                        success: function (data) {
                            instance.append($('<option/>', {
                                value: '0',
                                text: 'Choose the Isbn...',
                                disabled: true,
                                selected: true
                            }));
                            $(data).each(function (index, item) {
                                instance.append($('<option/>', { value: item.id, text: item.number }));
                            });
                        }
                    });
                }
            });

            $("#borrower").autocomplete({
                source: function (request, response) {
                    $.ajax({
                        url: "/Account/GetBorrower",
                        type: "POST",
                        dataType: "json",
                        data: { term: request.term },
                        success: function (data) {
                            response($.map(data, function (item) {
                                return { label: item.name, value: item.name };
                            }));
                        }
                    });
                },
                minLength: 5
            });
        });
    </script>
}

LibraryManagementApp/Views/BookIssue/Delete.cshtml
@model BookIssue
@{
    ViewData["Title"] = "Delete An Issue";
}

<div class="container">
    <p>
        <h4 class="text-center mt-2 mb-4">Are You Sure?</h4>
    </p>
    <div class="row">
        <div style="max-width: 450px; margin: auto;">
            <div class="text-center">
                <p class="mb-2">The following Issue will be deleted and all the Information will be lost!</p>
            </div>
            <div class="card mt-5">
                <table class="mt-3 mb-3 text-center text-white" style="display:flex; justify-content:center;">
                    <tbody>
                        <tr>
                            <td><strong>Borrower's Name:</strong></td>
                            <td>@Model.BorrowersName</td>
                        </tr>
                        <tr>
                            <td><strong>Isbn Number:</strong></td>
                            <td>@Model.BookInstance?.IsbnNumber</td>
                        </tr>
                        <tr>
                            <td><strong>Borrowed By:</strong></td>
                            <td>@Model.BorrowingLibrariansName</td>
                        </tr>
                        <tr>
                            <td><strong>Time Borrowed:</strong></td>
                            <td>@Model.TimeBorrowed</td>
                        </tr>
                        <tr>
                            <td><strong>Returned By:</strong></td>
                            <td>@Model.ReturningLibrariansName</td>
                        </tr>
                        <tr>
                            <td><strong>Time Returned:</strong></td>
                            <td>@Model.TimeReturned</td>
                        </tr>
                        <tr>
                            <td><strong>Due Date:</strong></td>
                            <td>@Model.DueDate</td>
                        </tr>
                        <tr>
                            <td><strong>Book Status:</strong></td>
                            <td>@Model.bookStatus</td>
                        </tr>
                        <tr>
                            <td><strong>Book Return Status:</strong></td>
                            <td>@Model.bookReturnStatus</td>
                        </tr>
                    </tbody>
                </table>
            </div>
        
            <div class="mt-5">
                <form asp-action="Delete">
                    <a asp-action="Index" class="btn btn-light">
                        <i class="bi bi-box-arrow-left"></i> Cancel
                    </a>
                    <input type="hidden" asp-for="Id" />
                    <button type="submit" class="btn btn-danger float-end">Confirm <i class="bi bi-trash3"></i></button>
                </form>
            </div>
        </div>
    </div>
</div>

LibraryManagementApp/Views/BookIssue/Details.cshtml
@using LibraryManagementApp.Enums
@model BookIssue
@{
    ViewData["Title"] = "Book Issue Details";
    string name = User.Identity.Name;
    var today = DateTime.Now.Date.ToString("yyyy-MM-dd");
}

<div class="row" style="margin: auto; display: flex; justify-content: center;">
    <div class="col" style="max-width: 500px;">
        <div class="card mt-5">
            <div class="card-header mt-2">
                @if (User.Identity.IsAuthenticated && User.IsInRole("Admin"))
                {
                    <a class="mt-2 float-end" asp-action="Edit" asp-route-id="@Model.Id">
                        <i class="bi bi-pencil-square"></i> Edit
                    </a>
                }
                <h4 class="text-center">Issue Details</h4>
            </div>
            <div class="card-body text-white text-center">
                <table style="display:flex; justify-content:center;">
                    <tbody>
                        <tr>
                            <td><strong>Borrower's Name:</strong></td>
                            <td>@Model.BorrowersName</td>
                        </tr>
                        <tr>
                            <td><strong>Isbn Number:</strong></td>
                            <td>@Model.BookInstance?.IsbnNumber</td>
                        </tr>
                        <tr>
                            <td><strong>Borrowed By:</strong></td>
                            <td>@Model.BorrowingLibrariansName</td>
                        </tr>
                        <tr>
                            <td><strong>Time Borrowed:</strong></td>
                            <td>@Model.TimeBorrowed</td>
                        </tr>

                        @if(Model.ReturningLibrariansName != null)
                        {
                            <tr>
                                <td><strong>Returned By:</strong></td>
                                <td>@Model.ReturningLibrariansName</td>
                            </tr>
                            <tr>
                                <td><strong>Time Returned:</strong></td>
                                <td>@Model.TimeReturned</td>
                            </tr>
                        }

                        <tr>
                            <td><strong>Due Date:</strong></td>
                            <td>@Model.DueDate</td>
                        </tr>
                        <tr>
                            <td><strong>Book Status:</strong></td>
                            <td>@Model.bookStatus</td>
                        </tr>
                        <tr>
                            <td><strong>Book Return Status:</strong></td>
                            <td>@Model.bookReturnStatus</td>
                        </tr>
                    </tbody>
                </table>
                <div class="mt-5">
                    <a class="btn btn-light float-start" asp-action="Index"><i class="bi bi-box-arrow-left"></i> Show All</a>
                    @if (Model.bookReturnStatus == BookReturnStatus.NotYetReturned)
                    {
                        <a class="btn btn-outline-success float-end" asp-action="ReturnBook" asp-route-id="@Model.Id"><i class="bi bi-check2-circle"></i> Return</a>
                    }
                </div>
            </div>
        </div>
    </div>
</div>

LibraryManagementApp/Views/BookIssue/History.cshtml
@using LibraryManagementApp.Enums
@model PaginatedList<BookIssue>

@{
    ViewData["Title"] = "Borrowers History";

    var viewData = new ViewDataDictionary(ViewData);
    viewData["Param1"] = ViewBag.searcheditem;
    viewData["actionPage"] = "History";
}
<div class="row">
    <h4 class="mt-3 mb-4 text-center"><i class="bi bi-clock-history"></i> History</h4>

    <div style="max-width:1100px; margin:auto;">
        <div class="row mb-3">
            <div class="col">
                @using (Html.BeginForm("History", "BookIssue", FormMethod.Get))
                {
                    <div class="row">
                        <div class="col-md-5">
                            <select name="searchString" class="form-select" asp-items="Html.GetEnumSelectList<BookReturnStatus>()"></select>
                        </div>
                        <div class="col">
                            <input class="btn btn-light float-start" value="Filter By Return Status" type="submit">
                        </div>
                    </div>
                }
            </div>
            <div class="col">
                <a class="btn btn-light float-end" asp-action="History">All</a>
            </div>
        </div>
        <table class="table">
            <thead>
                <tr class="text-center">
                    <th>@Html.DisplayNameFor(model => model.First().TimeBorrowed)</th>
                    <th>User</th>
                    <th>@Html.DisplayNameFor(model => model.First().bookStatus)</th>
                    <th>@Html.DisplayNameFor(model => model.First().BookInstance!.IsbnNumber)</th>
                    @*<th>Fined</th>*@
                    @if (User.Identity!.IsAuthenticated && User.IsInRole("Admin"))
                    {
                        <th>Action</th>
                    }
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td class="align-middle text-center">@Html.DisplayFor(modelItem => item.TimeBorrowed)</td>
                        <td class="align-middle text-center">@Html.DisplayFor(modelItem => item.BorrowersName)</td>
                        <td class="align-middle text-center">@Html.DisplayFor(modelItem => item.bookStatus)</td>
                        <td class="align-middle text-center">@Html.DisplayFor(modelItem => item.BookInstance!.IsbnNumber)</td>
                        @*<td class="align-middle text-center"><i class="bi bi-x-circle"></i></td>*@
                        @if (User.Identity.IsAuthenticated && User.IsInRole("Admin"))
                        {
                            <td class="text-center">
                                <a class="btn btn-outline-primary me-2" asp-action="Details" asp-route-id="@item.Id"><i class="bi bi-info-circle"></i></a>
                            </td>
                        }
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>

<partial name="_Pager" view-data="viewData" />

LibraryManagementApp/Views/BookIssue/Index.cshtml
@using LibraryManagementApp.Enums
@model PaginatedList<BookIssue>

@{
    ViewData["Title"] = "Issue a Book";
    var viewData = new ViewDataDictionary(ViewData);
    viewData["Param1"] = ViewBag.searcheditem;
    viewData["actionPage"] = "Index";
}
<div class="row">
    <h4 class="mt-3 mb-4 text-center"><i class="bi bi-journal-arrow-up"></i> Issued Books</h4>
    <div style="max-width:1200px; margin:auto;">
        <div class="row g-2 mb-3">
            <div class="col">
                @using (Html.BeginForm("Index", "BookIssue", FormMethod.Get))
                {
                    <div class="row">
                        <div class="col-md-7">
                            <input name="searchString" id="searchedString" class=" form-control" type="search" placeholder="Filter by email ...">
                        </div>
                        <div class="col">
                            <input class="btn btn-light float-start" value="Filter" type="submit">
                        </div>
                    </div>
                }
            </div>
            <div class="col">
                <div class="row float-end">
                    <div class="col">
                        <a class="btn btn-light" asp-action="Index">All</a>
                    </div>
                    <div class="col">
                        @using (Html.BeginForm("Index", "BookIssue", FormMethod.Get))
                        {
                            <input name="searchString" type="hidden" value="NotYetReturned" />
                            <input class="btn btn-light float-start" value="Borrowed" type="submit">
                        }
                    </div>
                </div>
            </div>
        </div>
        <table class="table">
            <thead>
                <tr class="text-center">
                    <th>@Html.DisplayNameFor(model => model.First().TimeBorrowed)</th>
                    <th>Borrower</th>
                    <th>Issued By</th>
                    <th>@Html.DisplayNameFor(model => model.First().bookStatus)</th>
                    <th>@Html.DisplayNameFor(model => model.First().BookInstance!.IsbnNumber)</th>
                    @if (User.Identity!.IsAuthenticated && (User.IsInRole("Admin") || User.IsInRole("Librarian")))
                    {
                        @*<th>Fines</th>*@
                        <th>Actions</th>
                    }
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td class="align-middle text-center">@Html.DisplayFor(modelItem => item.TimeBorrowed)</td>
                        <td class="align-middle text-center">@Html.DisplayFor(modelItem => item.BorrowersName)</td>
                        <td class="align-middle text-center">@Html.DisplayFor(modelItem => item.BorrowingLibrariansName)</td>
                        <td class="align-middle text-center">@Html.DisplayFor(modelItem => item.bookStatus)</td>
                        <td class="align-middle text-center">@Html.DisplayFor(modelItem => item.BookInstance!.IsbnNumber)</td>
                        @*<td class="align-middle text-center"><i class="bi bi-x-circle"></i></td>*@
                        <td class="text-center">
                            <a class="btn btn-outline-primary me-2" asp-action="Details" asp-route-id="@item.Id"><i class="bi bi-info-circle"></i> Info</a>
                            @if (User.Identity.IsAuthenticated && User.IsInRole("Admin"))
                            {
                                <a class="btn btn-light me-2" asp-action="Edit" asp-route-id="@item.Id"><i class="bi bi-pencil-square"></i> Edit</a>
                                @if (item.bookReturnStatus != BookReturnStatus.NotYetReturned)
                                {
                                    <a class="btn btn-outline-danger" asp-action="Delete" asp-route-id="@item.Id">
                                        <i class="bi bi-trash"></i> Delete
                                    </a>
                                }
                            }
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>

@if (User.Identity.IsAuthenticated && (User.IsInRole("Admin") || User.IsInRole("Librarian")))
{
    @await Html.PartialAsync("_CreateItem", "BookIssue")
}

<partial name="_Pager" view-data="viewData" />

@section scripts{
    <script>
        $(document).ready(function () {
            $("#searchedString").autocomplete({
                source: function (request, response) {
                    $.ajax({
                        url: "/Account/GetBorrower",
                        type: "POST",
                        dataType: "json",
                        data: { term: request.term },
                        success: function (data) {
                            response($.map(data, function (item) {
                                return { label: item.name, value: item.name };
                            }));
                        }
                    });
                },
                minLength: 5
            });
        });
    </script>
}