LibraryManagementApp/Models/Book.cs
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel.DataAnnotations;
using LibraryManagementApp.Enums;
using LibraryManagementApp.Data.Base;

namespace LibraryManagementApp.Models
{
    public class Book : IEntityBase
    {
        [Key]
        public int Id { get; set; }
        public string? Title { get; set; }
        public BookCategory bookCategory { get; set; }
        public string? Description { get; set; }
        //[DataType(DataType.Date)]
        //[DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public DateTime DateCreated { get; set; }
        public int AvailableAmount { get; set; }
        public int TotalAmount { get; set; }
        //[Range(1, 100)]
        //[DataType(DataType.Currency)]
        //[Column(TypeName = "decimal(18, 2)")]
        public decimal Price { get; set; }
        public string? Location { get; set; }
        public string? Image { get; set; }

        //Relationships
        public List<BookInstance>? BookInstance { get; set; }
        public List<Author_Book>? Author_Book { get; set; }
        public int PublisherId { get; set; }
        [ForeignKey("PublisherId")]
        public Publisher? Publisher { get; set; }
    }
}

LibraryManagementApp/Controllers/AuthorController.cs
using LibraryManagementApp.Data;
using LibraryManagementApp.Data.Services;
using LibraryManagementApp.Data.Static;
using LibraryManagementApp.Data.ViewModels;
using LibraryManagementApp.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Data;

namespace LibraryManagementApp.Controllers
{
    [Authorize(Roles = UserRoles.Admin + "," + UserRoles.Librarian)]
    public class AuthorController : Controller
    {
        private readonly IAuthorsService _service;

        public AuthorController(IAuthorsService service)
        {
            _service = service;
        }

        [AllowAnonymous]
        public async Task<IActionResult> Index()
        {
            var data = await _service.GetAllAsync();
            return View(data);
        }

        //Create
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(NewAuthorVM newAuthorVM)
        {
            if(!ModelState.IsValid)
            {
                return View(newAuthorVM);
            }

            await _service.AddNewAuthorAsync(newAuthorVM);
            return RedirectToAction(nameof(Index));
        }

        //Details
        [AllowAnonymous]
        public async Task<IActionResult> Details(int id)
        {
            var authorDetails = await _service.GetByIdAsync(id);
            if (authorDetails == null)
                return NotFound();
            return View(authorDetails);
        }

        //Edit
        public async Task<IActionResult> Edit(int id)
        {
            var authorDetails = await _service.GetByIdAsync(id);
            if (authorDetails == null)
                return NotFound();

            var response = new NewAuthorVM()
            {
                PreviewPicture = authorDetails.ProfilePicture,
                FullName = authorDetails.FullName,
                Biography = authorDetails.Biography
            };

            return View(response);
        }
        [HttpPost]
        public async Task<IActionResult> Edit(int id, NewAuthorVM newAuthorVM)
        {
            if (id != newAuthorVM.Id) return View("Not Found");

            if (ModelState.IsValid)
            {
                await _service.UpdateAuthorAsync(newAuthorVM);
                return RedirectToAction(nameof(Index));
            }
            return View(newAuthorVM);
        }

        //Delete
        [Authorize(Roles = UserRoles.Admin)]
        public async Task<IActionResult> Delete(int id)
        {
            var authorDetails = await _service.GetByIdAsync(id);
            if (authorDetails == null) return View("Not Found");
            return View(authorDetails);
        }
        [HttpPost, ActionName("Delete")]
        public async Task<IActionResult> DeleteConfirmed(int id, [Bind("Id, FullName, ProfilePicture, Biography")] Author author)
        {
            var authorDetails = await _service.GetByIdAsync(id);
            if (authorDetails == null) return View("Not Found");

            await _service.DeleteAsync(id);
            return RedirectToAction(nameof(Index));
        }
    }
}

LibraryManagementApp/Controllers/BookController.cs
using LibraryManagementApp.Data.ViewModels;
using LibraryManagementApp.Data.Services;
using LibraryManagementApp.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using static System.Runtime.InteropServices.JavaScript.JSType;
using LibraryManagementApp.Data.Static;
using Microsoft.AspNetCore.Authorization;
using System.Data;
using LibraryManagementApp.Data;
using System.Drawing.Printing;
using static System.Reflection.Metadata.BlobBuilder;
using LibraryManagementApp.Enums;

namespace LibraryManagementApp.Controllers
{
    [Authorize(Roles = UserRoles.Admin + "," + UserRoles.Librarian)]
    public class BookController : Controller
    {
        private readonly IBookService _service;

        public BookController(IBookService service)
        {
            _service = service;
        }

        [AllowAnonymous]
        public async Task<IActionResult> Index(int? i)
        {
            if (i < 1) i = 1;

            //var allBook = await _context.Book.Include(n => n.Publisher).OrderBy(n => n.Title).ToListAsync();
            var allBooks = await _service.GetAllAsync();
            var paginatedBookList = await PaginatedList<Book>.CreateAsync(allBooks, i ?? 1, 4);

            int totalPages = PageLength.Length;
            if (i > totalPages) i = totalPages;

            return View(paginatedBookList);
        }

        //Autocomplete for book search
        [AllowAnonymous]
        [HttpPost]
        public async Task<JsonResult> GetTitle(string term)
        {
            var allBooks = await _service.GetAllAsync();
            var results = allBooks.Where(i => i.Title!.ToLower().Contains(term.ToLower()))
                                         .Select(i => new { id = i.Id, name = i.Title })
                                         .ToList();

            return Json(results);
        }

        //Filter
        [AllowAnonymous]
        public async Task<IActionResult> Filter(string searchString)
        {
            var allBooks = await _service.GetAllAsync();

            if (!string.IsNullOrEmpty(searchString))
            {
                //var filteredResult = allBooks.Where(n => n.Title!.ToLower().Contains(searchString.ToLower()) ||
                  //n.Description!.ToLower().Contains(searchString.ToLower())).ToList();
                var filteredResultNew = allBooks.Where(n => string.Equals(n.Title, searchString, StringComparison.CurrentCultureIgnoreCase)).ToList();
                //|| string.Equals(n.Description, searchString, StringComparison.CurrentCultureIgnoreCase))

                //var simpleResult = allBooks.Where(n => n.Title!.ToLower().Contains(searchString.ToLower()));
                //var allBook2 = await PaginatedList<Book>.CreateAsync(simpleResult, i, 4);

                if(filteredResultNew.Count() > 0)
                {
                    ViewBag.Message = "Search results for \" " + searchString + " \" ...";
                    return View("SearchResults", filteredResultNew);
                }
                
                ViewBag.Message = "No results for ' " + searchString + " ' ...\n" +
                    "perhaps you could use the auto complete field to help you fill out the search bar if your results came up.";
                return View("SearchResults", filteredResultNew);
            }

            return RedirectToAction(nameof(Index));
        }

        //Details
        [AllowAnonymous]
        public async Task<IActionResult> Details(int id) 
        {
            var bookDetails = await _service.GetBookByIdAsync(id);
            if (bookDetails == null)
                return NotFound();

            return View(bookDetails);
        }

        //Create
        public async Task<IActionResult> Create()
        {
            var bookDropdownsData = await _service.GetNewBookDropdownsValues();

            ViewBag.Publishers = new SelectList(bookDropdownsData.Publishers, "Id", "PublisherName");
            ViewBag.Authors = new MultiSelectList(bookDropdownsData.Authors, "Id", "FullName");

            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Create(NewBookVM book)
        {
            if (!ModelState.IsValid)
            {
                var bookDropdownsData = await _service.GetNewBookDropdownsValues();

                ViewBag.Publishers = new SelectList(bookDropdownsData.Publishers, "Id", "PublisherName");
                ViewBag.Authors = new SelectList(bookDropdownsData.Authors, "Id", "FullName");

                return View(book);
            }

            if (book.Price < 0m)
            {
                TempData["Error"] = "The Price of a book cannot be negative!";

                var bookDropdownsData = await _service.GetNewBookDropdownsValues();
                ViewBag.Publishers = new SelectList(bookDropdownsData.Publishers, "Id", "PublisherName");
                ViewBag.Authors = new SelectList(bookDropdownsData.Authors, "Id", "FullName");
                return View(book);
            }
            await _service.AddNewBookAsync(book);
            return RedirectToAction(nameof(Index));
        }

        //Edit
        public async Task<IActionResult> Edit(int id)
        {
            var bookDetails = await _service.GetBookByIdAsync(id);
            if (bookDetails == null)
                return NotFound();

            var response = new NewBookVM()
            {
                Title = bookDetails.Title,
                bookCategory = bookDetails.bookCategory,
                Description = bookDetails.Description,
                DateCreated = bookDetails.DateCreated,
                //AvailableAmount = bookDetails.AvailableAmount,
                //TotalAmount = bookDetails.TotalAmount,
                Price = bookDetails.Price,
                Location = bookDetails.Location,
                ImagePreview = bookDetails.Image,
                PublisherId = bookDetails.PublisherId,
                AuthorIds = bookDetails.Author_Book?.Select(n => n.AuthorId).ToList(),
            };

            var bookDropdownsData = await _service.GetNewBookDropdownsValues();

            ViewBag.Publishers = new SelectList(bookDropdownsData.Publishers, "Id", "PublisherName");
            ViewBag.Authors = new SelectList(bookDropdownsData.Authors, "Id", "FullName");

            return View(response);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(int id, NewBookVM newBookVM)
        {
            if (id != newBookVM.Id) return View("Not Found");

            if (ModelState.IsValid)
            {
                await _service.UpdateBookAsync(newBookVM);
                return RedirectToAction(nameof(Index));
            }

            var bookDropdownsData = await _service.GetNewBookDropdownsValues();

            ViewBag.Publishers = new SelectList(bookDropdownsData.Publishers, "Id", "PublisherName");
            ViewBag.Authors = new SelectList(bookDropdownsData.Authors, "Id", "FullName");

            return View(newBookVM);
        }
    }
}

LibraryManagementApp/Controllers/OrdersController.cs
using LibraryManagementApp.Data.Cart;
using LibraryManagementApp.Data.Services;
using LibraryManagementApp.Data.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;

namespace LibraryManagementApp.Controllers
{
    [Authorize]
    public class OrdersController : Controller
    {
        private readonly IBookService _bookService;
        private readonly Busket _busket;
        private readonly IOrdersService _ordersService;

        public OrdersController(IBookService bookService, Busket busket, IOrdersService ordersService)
        {
            _bookService = bookService;
            _busket = busket;
            _ordersService = ordersService;
        }

        public async Task<IActionResult> Index()
        {
            string userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            string userRole = User.FindFirstValue(ClaimTypes.Role);

            var orders = await _ordersService.GetOrdersByUserIdAndRoleAsync(userId, userRole);
            return View(orders);
        }

        public IActionResult Busket()
        {
            var items = _busket.GetBusketItems();
            _busket.BusketItems = items;

            var response = new BusketVM()
            {
                Busket = _busket,
                BusketTotal = _busket.GetBusketTotal()
            };

            return View(response);
        }

        public async Task<IActionResult> AddItemToBusket(int id)
        {
            var item = await _bookService.GetBookByIdAsync(id);

            if (item != null)
            {
                _busket.AddItemToBusket(item);
            }
            return RedirectToAction(nameof(Busket));
        }

        public async Task<IActionResult> RemoveItemFromBusket(int id)
        {
            var item = await _bookService.GetBookByIdAsync(id);

            if (item != null)
            {
                _busket.RemoveItemFromBusket(item);
            }
            return RedirectToAction(nameof(Busket));
        }

        public async Task<IActionResult> CompleteOrder()
        {
            var items = _busket.GetBusketItems();
            string userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            string userEmailAddress = User.FindFirstValue(ClaimTypes.Email);

            await _ordersService.StoreOrderAsync(items, userId, userEmailAddress);
            await _busket.ClearBusketAsync();

            return View("OrderCompleted");
        }
    }
}

LibraryManagementApp/Controllers/PublishersController.cs
using LibraryManagementApp.Data;
using LibraryManagementApp.Data.Services;
using LibraryManagementApp.Data.Static;
using LibraryManagementApp.Data.ViewModels;
using LibraryManagementApp.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Data;

namespace LibraryManagementApp.Controllers
{
    [Authorize(Roles = UserRoles.Admin + "," + UserRoles.Librarian)]
    public class PublishersController : Controller
    {
        private readonly IPublishersService _service;

        public PublishersController(IPublishersService service)
        {
            _service = service;
        }

        [AllowAnonymous]
        public async Task<IActionResult> Index()
        {
            var allPublishers = await _service.GetAllAsync();
            return View(allPublishers);
        }

        //Create
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(NewPublisherVM publisherVM)
        {
            if (!ModelState.IsValid)
            {
                return View(publisherVM);
            }
            await _service.AddNewPublisherAsync(publisherVM);
            return RedirectToAction(nameof(Index));
        }

        //Details
        [AllowAnonymous]
        public async Task<IActionResult> Details(int id)
        {
            var publishersDetails = await _service.GetByIdAsync(id);
            if (publishersDetails == null)
                return NotFound();
            return View(publishersDetails);
        }

        //Edit
        public async Task<IActionResult> Edit(int id)
        {
            var publisherDetails = await _service.GetByIdAsync(id);
            if (publisherDetails == null)
                return NotFound();

            var response = new NewPublisherVM()
            {
                PublisherLogoPreview = publisherDetails.PublisherLogo,
                PublisherName = publisherDetails.PublisherName,
                PublisherDescription = publisherDetails.PublisherDescription,
                Rating = publisherDetails.Rating
            };

            return View(response);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(int id, NewPublisherVM publisherVM)
        {
            if (id != publisherVM.Id) return View("Not Found");

            if (ModelState.IsValid)
            {
                await _service.UpdatePublisherAsync(publisherVM);
                return RedirectToAction(nameof(Index));
            }
            return View(publisherVM);
        }

        //Delete
        [Authorize(Roles = UserRoles.Admin)]
        public async Task<IActionResult> Delete(int id)
        {
            var publisherDetails = await _service.GetByIdAsync(id);
            if (publisherDetails == null) return View("Not Found");
            return View(publisherDetails);
        }

        [HttpPost, ActionName("Delete")]
        public async Task<IActionResult> DeleteConfirmed(int id, [Bind("Id, FullName, ProfilePicture, Biography")] Publisher publisher)
        {
            var publisherDetails = await _service.GetByIdAsync(id);
            if (publisherDetails == null) return View("Not Found");

            await _service.DeleteAsync(id);
            return RedirectToAction(nameof(Index));
        }
    }
}

LibraryManagementApp/Views/Book/Create.cshtml
@using LibraryManagementApp.Data.ViewModels;
@using LibraryManagementApp.Enums;
@model NewBookVM

@{
    ViewData["Title"] = "Create a new Book";
}

<div class="container">
    <h4 class="text-center mt-4 mb-3">Create a new Book</h4>
    <div class="row">
        <form asp-action="Create" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>

            <div class="row g-3" style="width:900px; margin:auto;">
                @if (TempData["Error"] != null)
                {
                    <div class="alert alert-danger text-center mb-3" style="margin:auto;">
                        <small>@TempData["Error"]</small>
                    </div>
                }
                <div class="col-md-8 bg-light" style="border-radius:4px; padding-bottom:5px;">
                    <div class="row g-2 mt-1">
                        <div class="col-md-6">
                            <label asp-for="Title" class="form-label">Title:</label>
                            <input asp-for="Title" type="text" class="form-control" id="inputTitle">
                            <span asp-validation-for="Title" class="text-danger"></span>
                        </div>
                        <div class="col-md-6">
                            <label asp-for="DateCreated" class="form-label">Created On:</label>
                            <input asp-for="DateCreated" type="date" class="form-control" id="inputDate">
                            <span asp-validation-for="DateCreated" class="text-danger"></span>
                        </div>
                        <div class="col-md-6">
                            <label asp-for="Price" class="form-label">Price:</label>
                            <div class="input-group flex-nowrap">
                                <span class="input-group-text" id="addon-wrapping">$</span>
                                <input asp-for="Price" min="1" class="form-control" aria-describedby="addon-wrapping">
                            </div>
                            <span asp-validation-for="Price" class="text-danger"></span>
                        </div>
                        <div class="col-md-6">
                            <label asp-for="PublisherId" class="form-label">Select a Publisher:</label>
                            <select asp-for="PublisherId" class="form-control form-select" asp-items="ViewBag.Publishers"></select>
                            <span asp-validation-for="PublisherId" class="text-danger"></span>
                        </div>
                        <div class="col-md-6">
                            <label asp-for="bookCategory" class="form-label">Category:</label>
                            <select asp-for="bookCategory" class="form-control form-select" asp-items="Html.GetEnumSelectList<BookCategory>()"></select>
                            <span asp-validation-for="bookCategory" class="text-danger"></span>
                        </div>
                        <div class="col-md-6">
                            <label asp-for="Image" class="form-label">Image:</label>
                            <input asp-for="Image" class="form-control" id="fileUpload" onchange="getImagePreview(event)">
                            <span asp-validation-for="Image" class="text-danger"></span>
                        </div>
                        <div class="col-md-6">
                            <label asp-for="AuthorIds" class="form-label">Select the Author(s):</label>
                            <select asp-for="AuthorIds" class="form-control" asp-items="ViewBag.Authors" multiple></select>
                            <span asp-validation-for="AuthorIds" class="text-danger"></span>
                        </div>
                        <div class="col-md-6">
                            <label asp-for="Description" class="form-label">Description:</label>
                            <textarea asp-for="Description" class="form-control" id="inputDescription" rows="4"></textarea>
                            <span asp-validation-for="Description" class="text-danger"></span>
                        </div>
                        <div class="col-md-12">
                            <label asp-for="Location" class="form-label">Location:</label>
                            <input asp-for="Location" type="text" class="form-control" id="inputLocation">
                            <span asp-validation-for="Location" class="text-danger"></span>
                        </div>
                    </div>
                </div>
                <div class="col-md-4">
                    <img class="card-img-top mt-2" id="imagePreview" style="border-radius: 5px; padding-top: 2px;" alt="Image for the new Book">
                </div>
                <div class="row g-2 mt-3">
                    <div class="col-md-6">
                        <a class="float-start btn btn-light" asp-action="Index">
                            <i class="bi bi-arrow-left-circle"></i> Back to List
                        </a>
                    </div>
                    <div class="col-md-6">
                        <button type="submit" class="float-end btn btn-outline-success">Create Book <i class="bi bi-journal-check"></i></i></button>
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>

@section Scripts{
    <script>
        function getImagePreview(event) {
            var image = URL.createObjectURL(event.target.files[0]);
            console.log(event.target.files[0]);
            var previewSection = document.getElementById('imagePreview');
            previewSection.src = image;
        }
    </script>
}

LibraryManagementApp/Views/Book/Details.cshtml
@model Book
@{
    ViewData["Title"] = "Book Details";
}

<div class="row" style="max-width: 1240px; margin:auto;">
    <div class="col-md-9" style="padding-left:30px;">
        <div class="card mt-5" style="max-width: 850px;">
            <div class="card-body">
                <div class="row">
                    <div class="col-md-5">
                        <img src="~/images/Books/@Model.Image" class="card-img-top" alt="Image for @Model.Title">
                    </div>
                    <div class="col-md-7">
                        <div class="row">
                            <div class="card-header">
                                @if (User.Identity!.IsAuthenticated && (User.IsInRole("Admin") || User.IsInRole("Librarian")))
                                {
                                    <h5 class="card-title float-start"><strong>@Model.Title</strong></h5>
                                    <a asp-action="Edit" asp-route-id="@Model.Id">
                                        <small class="float-end text-body-secondary"><i class="bi bi-pencil-square"></i> Edit</small>
                                    </a>
                                }
                                else
                                {
                                    <h5 class="card-title float-start"><strong>@Model.Title</strong></h5>
                                }
                            </div>
                            <div class="card-text mt-3">
                                Description:<br />
                                <strong class="text-white">@Model.Description</strong>
                            </div>
                            <p class="card-text mt-4">
                                Category: <strong class="text-white">@Model.bookCategory</strong><br />
                                Created On: <strong class="text-white">@Model.DateCreated.ToString("dd MMM yy")</strong><br />
                                Status: 
                                @if (Model.AvailableAmount > 0)
                                {
                                    <span class="badge rounded-pill text-bg-success">Available</span>
                                }
                                else
                                {
                                    <span class="badge rounded-pill text-bg-primary">UpComing</span>
                                }
                            </p>
                            @*<h2>Copies:</h2>
                            <ul>
                                \foreach (var copy in Model.Copies)
                                {
                                    <li>\copy.Id</li>
                                }
                            </ul>*@
                        </div>
                    
                    </div>
                </div>
            </div>
            <div class="card-footer">
                <a class="float-start btn btn-light" asp-action="Index"><i class="bi bi-arrow-left-circle"></i> Back to List</a>
                @*<a class="btn btn-warning float-end  @((Model.AvailableAmount > 0) ? "" : "disabled")"
                   asp-controller="Orders"
                   asp-action="AddItemToBusket" asp-route-id="@Model.Id">
                    <i class="bi bi-cart-plus"></i> Reserve a copy (Price @Model.Price.ToString("c"))
                </a>
                <button type="button" class="float-end btn btn-warning">Add to Busket <i class="bi bi-archive"></i></button>*@
            </div>
        </div>
    </div>
    <div class="col-md-3 mt-5" style="max-width:350px; padding-left:50px;">
        <div class="row">
            <p class="card-text mt-4">About the Author(s):</p>
            <div class="row">
                @foreach (var author in Model.Author_Book)
                {
                    <div class="col text-center mt-2">
                        <p class="card-text" style="max-width:100px;">
                            <a asp-controller="Author" asp-action="Details" asp-route-id="@author.AuthorId" style="text-decoration:none;">
                                <img class="rounded-circle" src="~/Images/Authors/@author.Author?.ProfilePicture" alt="Image for @author.Author?.FullName" style="width: 100px;">
                                <br />
                                <strong>@author.Author?.FullName</strong>
                            </a>
                        </p>
                    </div>
                }
            </div>
        </div>
        <div class="row mt-5">
            <p class="card-text mt-4">Publisher:</p>
            <div class="col text-center mt-2">
                <p class="card-text" style="max-width:100px;">
                    <a asp-controller="Publishers" asp-action="Details" asp-route-id="@Model.PublisherId" style="text-decoration:none;">
                        <img class="rounded-circle" src="~/Images/Publishers/@Model.Publisher?.PublisherLogo" alt="Image for @Model.Publisher?.PublisherName" style="width: 100px;">
                        <br />
                        <strong>@Model.Publisher?.PublisherName</strong>
                    </a>
                </p>
            </div>
        </div>
    </div>
</div>

LibraryManagementApp/Views/Book/SearchResults.cshtml
@model List<Book>

@{
    ViewData["Title"] = "Search Results";
    string msg = ViewBag.Message;
}

<h5 class="mt-4 text-center">@msg</h5>

<div class="container" id="element3">
    <div class="row row-cols-1 row-cols-md-4 g-4 mt-4">
        @foreach (var item in Model)
        {
            <div class="col">
                <div class="card" style="width: 270px;">
                    @if (User.Identity!.IsAuthenticated && User.IsInRole("Admin"))
                    {
                        <div class="card-header">
                            <a class="float-start" asp-controller="Book" asp-action="Edit" asp-route-id="@item.Id">
                                <small class="text-body-secondary"><i class="bi bi-pencil-square"></i> Edit</small>
                            </a>
                        </div>
                    }
                    <a asp-controller="Book" asp-action="Details" asp-route-id="@item.Id">
                        <img src="~/images/Books/@item.Image" class="card-img-top" alt="Click here to view @item.Title" style="max-height:400px;" />
                    </a>
                    <div class="card-body">
                        <div class="row">
                            <h4 class="card-title"><strong>@item.Title</strong></h4>
                            <div class="col-md-9"><small class="card-text">Category: <strong>@item.bookCategory</strong></small></div>
                            <div class="col-md-3">
                                @if (item.AvailableAmount > 0)
                                {
                                    <span class="float-end badge rounded-pill text-bg-success">Available</span>
                                }
                                else
                                {
                                    <span class="float-end badge rounded-pill text-bg-primary">UpComing</span>
                                }
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        }
    </div>
</div>

@section scripts{
    <script>
        const element3 = document.getElementById('element3');
        TweenMax.from(element3, 1, { opacity: 0, delay: .15, y: -30, ease: Expo.easeInOut })
    </script>
}