LibraryManagementApp/Models/BookInstance.cs
using LibraryManagementApp.Enums;
using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel.DataAnnotations;
using LibraryManagementApp.Data.Base;

namespace LibraryManagementApp.Models
{
    public class BookInstance : IEntityBase
    {
        [Key]
        public int Id { get; set; }

        [Required(ErrorMessage = "The Isbn Number should be Provided!")]
        public string? IsbnNumber { get; set; }

        [Required(ErrorMessage = "The Status should be stated!")]
        public BookStatus bookStatus { get; set; }

        [Required(ErrorMessage = "The Availability should be stated!")]
        public BookAvailability bookAvailability { get; set; }

        //Relationships
        [Required(ErrorMessage = "The Book should be specified!")]
        public int BookId { get; set; }
        [ForeignKey("BookId")]
        public Book? Book { get; set; }

        public List<BookIssue>? BookIssue { get; set; }
    }
}

LibraryManagementApp/Controllers/BookController.cs
using LibraryManagementApp.Data.ViewModels;
using LibraryManagementApp.Data.Services;
using LibraryManagementApp.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using static System.Runtime.InteropServices.JavaScript.JSType;
using LibraryManagementApp.Data.Static;
using Microsoft.AspNetCore.Authorization;
using System.Data;
using LibraryManagementApp.Data;
using System.Drawing.Printing;
using static System.Reflection.Metadata.BlobBuilder;
using LibraryManagementApp.Enums;

namespace LibraryManagementApp.Controllers
{
    [Authorize(Roles = UserRoles.Admin + "," + UserRoles.Librarian)]
    public class BookController : Controller
    {
        private readonly IBookService _service;

        public BookController(IBookService service)
        {
            _service = service;
        }

        [AllowAnonymous]
        public async Task<IActionResult> Index(int? i)
        {
            if (i < 1) i = 1;

            //var allBook = await _context.Book.Include(n => n.Publisher).OrderBy(n => n.Title).ToListAsync();
            var allBooks = await _service.GetAllAsync();
            var paginatedBookList = await PaginatedList<Book>.CreateAsync(allBooks, i ?? 1, 4);

            int totalPages = PageLength.Length;
            if (i > totalPages) i = totalPages;

            return View(paginatedBookList);
        }

        //Autocomplete for book search
        [AllowAnonymous]
        [HttpPost]
        public async Task<JsonResult> GetTitle(string term)
        {
            var allBooks = await _service.GetAllAsync();
            var results = allBooks.Where(i => i.Title!.ToLower().Contains(term.ToLower()))
                                         .Select(i => new { id = i.Id, name = i.Title })
                                         .ToList();

            return Json(results);
        }

        //Filter
        [AllowAnonymous]
        public async Task<IActionResult> Filter(string searchString)
        {
            var allBooks = await _service.GetAllAsync();

            if (!string.IsNullOrEmpty(searchString))
            {
                //var filteredResult = allBooks.Where(n => n.Title!.ToLower().Contains(searchString.ToLower()) ||
                  //n.Description!.ToLower().Contains(searchString.ToLower())).ToList();
                var filteredResultNew = allBooks.Where(n => string.Equals(n.Title, searchString, StringComparison.CurrentCultureIgnoreCase)).ToList();
                //|| string.Equals(n.Description, searchString, StringComparison.CurrentCultureIgnoreCase))

                //var simpleResult = allBooks.Where(n => n.Title!.ToLower().Contains(searchString.ToLower()));
                //var allBook2 = await PaginatedList<Book>.CreateAsync(simpleResult, i, 4);

                if(filteredResultNew.Count() > 0)
                {
                    ViewBag.Message = "Search results for \" " + searchString + " \" ...";
                    return View("SearchResults", filteredResultNew);
                }
                
                ViewBag.Message = "No results for ' " + searchString + " ' ...\n" +
                    "perhaps you could use the auto complete field to help you fill out the search bar if your results came up.";
                return View("SearchResults", filteredResultNew);
            }

            return RedirectToAction(nameof(Index));
        }

        //Details
        [AllowAnonymous]
        public async Task<IActionResult> Details(int id) 
        {
            var bookDetails = await _service.GetBookByIdAsync(id);
            if (bookDetails == null)
                return NotFound();

            return View(bookDetails);
        }

        //Create
        public async Task<IActionResult> Create()
        {
            var bookDropdownsData = await _service.GetNewBookDropdownsValues();

            ViewBag.Publishers = new SelectList(bookDropdownsData.Publishers, "Id", "PublisherName");
            ViewBag.Authors = new MultiSelectList(bookDropdownsData.Authors, "Id", "FullName");

            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Create(NewBookVM book)
        {
            if (!ModelState.IsValid)
            {
                var bookDropdownsData = await _service.GetNewBookDropdownsValues();

                ViewBag.Publishers = new SelectList(bookDropdownsData.Publishers, "Id", "PublisherName");
                ViewBag.Authors = new SelectList(bookDropdownsData.Authors, "Id", "FullName");

                return View(book);
            }

            if (book.Price < 0m)
            {
                TempData["Error"] = "The Price of a book cannot be negative!";

                var bookDropdownsData = await _service.GetNewBookDropdownsValues();
                ViewBag.Publishers = new SelectList(bookDropdownsData.Publishers, "Id", "PublisherName");
                ViewBag.Authors = new SelectList(bookDropdownsData.Authors, "Id", "FullName");
                return View(book);
            }
            await _service.AddNewBookAsync(book);
            return RedirectToAction(nameof(Index));
        }

        //Edit
        public async Task<IActionResult> Edit(int id)
        {
            var bookDetails = await _service.GetBookByIdAsync(id);
            if (bookDetails == null)
                return NotFound();

            var response = new NewBookVM()
            {
                Title = bookDetails.Title,
                bookCategory = bookDetails.bookCategory,
                Description = bookDetails.Description,
                DateCreated = bookDetails.DateCreated,
                //AvailableAmount = bookDetails.AvailableAmount,
                //TotalAmount = bookDetails.TotalAmount,
                Price = bookDetails.Price,
                Location = bookDetails.Location,
                ImagePreview = bookDetails.Image,
                PublisherId = bookDetails.PublisherId,
                AuthorIds = bookDetails.Author_Book?.Select(n => n.AuthorId).ToList(),
            };

            var bookDropdownsData = await _service.GetNewBookDropdownsValues();

            ViewBag.Publishers = new SelectList(bookDropdownsData.Publishers, "Id", "PublisherName");
            ViewBag.Authors = new SelectList(bookDropdownsData.Authors, "Id", "FullName");

            return View(response);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(int id, NewBookVM newBookVM)
        {
            if (id != newBookVM.Id) return View("Not Found");

            if (ModelState.IsValid)
            {
                await _service.UpdateBookAsync(newBookVM);
                return RedirectToAction(nameof(Index));
            }

            var bookDropdownsData = await _service.GetNewBookDropdownsValues();

            ViewBag.Publishers = new SelectList(bookDropdownsData.Publishers, "Id", "PublisherName");
            ViewBag.Authors = new SelectList(bookDropdownsData.Authors, "Id", "FullName");

            return View(newBookVM);
        }
    }
}

LibraryManagementApp/Controllers/BookInstanceController.cs
using LibraryManagementApp.Data.Services;
using LibraryManagementApp.Data.Static;
using LibraryManagementApp.Data.ViewModels;
using LibraryManagementApp.Enums;
using LibraryManagementApp.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace LibraryManagementApp.Controllers
{
    [Authorize(Roles = UserRoles.Admin + "," + UserRoles.Librarian)]
    public class BookInstanceController : Controller
    {
        private readonly IBookInstanceService _service;

        public BookInstanceController(IBookInstanceService service)
        {
            _service = service;
        }

        public async Task<IActionResult> Index(int? i, string? searchString)
        {
            if (i < 1) i = 1;
            var allData = await _service.GetAllAsync(n => n.Book);

            if (searchString != null)
            {
                var filteredData = allData.Where(n => n.Book!.Title!.Equals(searchString));
                var filterPagedData = await PaginatedList<BookInstance>.CreateAsync(filteredData, i ?? 1, 8);
                ViewBag.searcheditem = searchString;

                return View(filterPagedData);
            }

            var paginatedData = await PaginatedList<BookInstance>.CreateAsync(allData, i ?? 1, 8);

            int totalPages = PageLength.Length;
            if (i > totalPages) i = totalPages;

            return View(paginatedData);
        }

        //json get the instances that are labled "Availabe"
        public async Task<JsonResult> GetInstance(int bookId)
        {
            var allInstances = await _service.GetAllAsync();
            var results = allInstances.Where(i => i.BookId.Equals(bookId) && i.bookAvailability.Equals(
                                            BookAvailability.Available))
                                         .Select(i => new { id = i.Id, number = i.IsbnNumber })
                                         .ToList();

            return Json(results);
        }

        //Create
        public async Task<IActionResult> Create()
        {
            var bookInstanceDropDownsData = await _service.GetBookInstanceDropDownsValues();

            ViewBag.Books = new SelectList(bookInstanceDropDownsData.Books, "Id", "Title");

            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Create(BookInstance bookInstance) 
        {
            if (!ModelState.IsValid)
            {
                var bookInstanceDropDownsData = await _service.GetBookInstanceDropDownsValues();
                ViewBag.Books = new SelectList(bookInstanceDropDownsData.Books, "Id", "Title");
                return View(bookInstance);
            }

            await _service.AddNewBookInstanceAsync(bookInstance);
            return RedirectToAction(nameof(Index));
        }

        //Edit
        public async Task<IActionResult> Edit(int id)
        {
            var instanceDetails = await _service.GetByIdAsync(id);
            if (instanceDetails == null)
                return NotFound();

            var response = new BookInstance()
            {
                IsbnNumber = instanceDetails.IsbnNumber,
                bookStatus = instanceDetails.bookStatus,
                BookId = instanceDetails.BookId
            };
            var bookInstanceDropDownsData = await _service.GetBookInstanceDropDownsValues();
            ViewBag.Books = new SelectList(bookInstanceDropDownsData.Books, "Id", "Title");

            return View(response);
        }
        [HttpPost]
        public async Task<IActionResult> Edit(int id, BookInstance bookInstance)
        {
            if (id != bookInstance.Id) return View("Not Found");

            if (ModelState.IsValid)
            {
                await _service.UpdateBookInstanceAsync(bookInstance);
                return RedirectToAction(nameof(Index));
            }
            var bookInstanceDropDownsData = await _service.GetBookInstanceDropDownsValues();
            ViewBag.Books = new SelectList(bookInstanceDropDownsData.Books, "Id", "Title");

            return View(bookInstance);
        }

        //Details
        [AllowAnonymous]
        public async Task<IActionResult> Details(int id)
        {
            var bookInstanceDetails = await _service.GetByIdAsync(id, n => n.Book);
            if (bookInstanceDetails == null)
                return NotFound();
            return View(bookInstanceDetails);
        }

        //Delete
        public async Task<IActionResult> Delete(int id)
        {
            var bookInstanceDetails = await _service.GetByIdAsync(id, n => n.Book);
            if (bookInstanceDetails == null) return View("Not Found");
            return View(bookInstanceDetails);
        }
        [HttpPost, ActionName("Delete")]
        public async Task<IActionResult> DeleteConfirmed(int id, BookInstance bookInstance)
        {
            var bookInstanceDetails = await _service.GetByIdAsync(id);
            if (bookInstanceDetails == null) return View("Not Found");

            await _service.DeleteAsync(id);
            return RedirectToAction(nameof(Index));
        }
    }
}

LibraryManagementApp/Views/BookInstance/Create.cshtml
@using LibraryManagementApp.Enums;
@using LibraryManagementApp.Data.ViewModels;
@model BookInstance

@{
    ViewData["Title"] = "Create an Instance of a Book";
}

<div class="row text mb-3">
    <div class="col-md-8 offset-2">
        <h4 class="text-center mt-3 mb-5">Create a new Book Instance</h4>
        <div class="row">
            <div class="col-md-8 offset-2">
                <form asp-action="Create">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <div class="row" style="max-width:500px; margin:auto;">
                        <div class="form-group mb-2">
                            <label asp-for="BookId" class="form-label">Book:</label>
                            <select asp-for="BookId" class="form-control form-select" asp-items="ViewBag.Books"></select>
                            <span asp-validation-for="BookId" class="text-danger"></span>
                        </div>
                        <div class="form-group mb-2">
                            <label asp-for="IsbnNumber" class="form-label">Isbn Number:</label>
                            <input asp-for="IsbnNumber" class="form-control" />
                            <span asp-validation-for="IsbnNumber" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="bookStatus" class="form-label">Book Status:</label>
                            <select asp-for="bookStatus" class="form-select">
                                <option>New</option>
                                <option>Good</option>
                                <option>MinimumDamage</option>
                                <option>Damaged</option>
                            </select>
                            <span asp-validation-for="bookStatus" class="text-danger"></span>
                        </div>
                        <div class="form-group mt-4">
                            <a class="btn btn-light" asp-action="Index"><i class="bi bi-box-arrow-left"></i> Show All</a>
                            <button type="submit" class="float-end btn btn-outline-success">
                                Create <i class="bi bi-check2-circle"></i>
                            </button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

<div class="mt-5 text-center">
    <p>Is the Book is Unavailabe? <a asp-controller="Book" asp-action="Create">Click here to create a new Book.</a></p>
</div>

@section Scripts{
    <script>
        $("#Image").on("change", function () {
            var output = document.getElementById("ImagePreview");
            output.src = $(this).val();
        })
    </script>
}

LibraryManagementApp/Views/BookInstance/Delete.cshtml
@model BookInstance
@{
    ViewData["Title"] = "Delete a Book Instance";
}

<div class="container">
    <p>
        <h4 class="text-center mt-3 mb-4">Are You Sure?</h4>
    </p>
    <div class="row">
        <div style="max-width: 450px; margin: auto;">
            <div class="text-center">
                <p class="mb-2">The following Instance will be deleted and all the Information will be lost!</p>
            </div>
            <div class="card" style="margin-top:70px;">
                <div class="card-body text-white">
                    <div class="mb-2">
                        <h5><strong>Book:</strong> @Model.Book!.Title</h5>
                    </div>
                    <div class="mb-2">
                        <h5><strong>Isbn Number:</strong> @Model.IsbnNumber</h5>
                    </div>
                    <div class="mb-2">
                        <h5><strong>Book Status:</strong> @Model.bookStatus</h5>
                    </div>
                    <div>
                        <h5><strong>Book Availability:</strong> @Model.bookAvailability</h5>
                    </div>
                </div>
            </div>
        
            <div style="margin-top:140px;">
                <form asp-action="Delete">
                    <a asp-action="Index" class="btn btn-light">
                        <i class="bi bi-box-arrow-left"></i> Cancel
                    </a>
                    <input type="hidden" asp-for="Id" />
                    <button type="submit" class="btn btn-danger float-end">Confirm <i class="bi bi-trash3"></i></button>
                </form>
            </div>
        </div>
    </div>
</div>

LibraryManagementApp/Views/BookInstance/Details.cshtml
@using LibraryManagementApp.Enums;
@model BookInstance

@{
    ViewData["Title"] = "Book Instance Details";
}

<div class="row" style="margin: auto; display: flex; justify-content: center; max-width: 500px;">
    <h4 class="text-center mt-3 mb-5">Book Instance Details</h4>
    <div class="row">
        <div>
            <div class="mt-5 mb-2">
                <h5><strong>Book:</strong> @Model.Book!.Title</h5>
            </div>
            <div class="mb-2">
                <h5><strong>Isbn Number:</strong> @Model.IsbnNumber</h5>
            </div>
            <div class="mb-2">
                <h5><strong>Book Status:</strong> @Model.bookStatus</h5>
            </div>
            <div class="mb-5">
                <h5><strong>Book Availability:</strong> @Model.bookAvailability</h5>
            </div>
        </div>
        <div style="margin-top:160px;">
            <a class="btn btn-light" asp-action="Index"><i class="bi bi-box-arrow-left"></i> Show All</a>
            @if (Model.bookAvailability != BookAvailability.Borrowed)
            {
                <a class="btn btn-outline-warning float-end" asp-action="Edit" asp-route-id="@Model.Id">
                    Edit <i class="bi bi-pencil-square"></i>
                </a>
            }
        </div>
    </div>
</div>

LibraryManagementApp/Views/BookInstance/Edit.cshtml
@using LibraryManagementApp.Enums;
@model BookInstance

@{
    ViewData["Title"] = "Edit A Book Instance";
}

<div class="container">
    <div class="row">
        <h4 class="text-center mt-3 mb-5">Edit An Instance</h4>

        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="card" style="margin:auto; max-width:400px;">
                <div class="card-body">
                    <div class="form-group mb-2">
                        <label asp-for="BookId" class="form-label">Book: </label>
                        <select asp-for="BookId" class="form-control form-select" asp-items="ViewBag.Books"></select>
                        <span asp-validation-for="BookId" class="text-danger"></span>
                    </div>
                    <div class="form-group mb-2">
                        <label asp-for="IsbnNumber" class="form-label">Isbn Number: </label>
                        <input asp-for="IsbnNumber" class="form-control" />
                        <span asp-validation-for="IsbnNumber" class="text-danger"></span>
                    </div>
                    <div class="form-group mb-2">
                        <label asp-for="bookStatus" class="form-label">Book Status: </label>
                        <select asp-for="bookStatus" class="form-control form-select" asp-items="Html.GetEnumSelectList<BookStatus>()"></select>
                        <span asp-validation-for="bookStatus" class="text-danger"></span>
                    </div>
                    <div class="form-group mt-4">
                        <a class="btn btn-light" asp-action="Index"><i class="bi bi-box-arrow-left"></i> Show All</a>
                        <button type="submit" class="float-end btn btn-outline-warning">
                            Save & Update <i class="bi bi-cloud-check"></i>
                        </button>
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>

@section Scripts{
    <script>
        $(document).ready(function () {
            var output = document.getElementById("ImagePreview");
            output.src = $("#Image").val();
        });
        $("#Image").on("change", function () {
            var output = document.getElementById("ImagePreview");
            output.src = $(this).val();
        })
    </script>
}

LibraryManagementApp/Views/BookInstance/Index.cshtml
@using LibraryManagementApp.Enums;
@model PaginatedList<BookInstance>


@{
    ViewData["Title"] = "View Book Inventory";
    var viewData = new ViewDataDictionary(ViewData);
    viewData["Param1"] = ViewBag.searcheditem;
    viewData["actionPage"] = "Index";
}

<div class="row">
    <h4 class="mt-3 mb-4 text-center"><i class="bi bi-archive"></i> Inventory</h4>
    <div class="col-md-8 offset-2 mb-3">
        <div class="row">
            <div class="col">
                @using (Html.BeginForm("Index", "BookInstance", FormMethod.Get))
                {
                    <div class="row">
                        <div class="col-md-7">
                            <input name="searchString" id="searchedString" class=" form-control" type="search" placeholder="Filter by Book title ...">
                        </div>
                        <div class="col">
                            <input class="btn btn-light float-start" value="Filter" type="submit">
                        </div>
                    </div>
                }
            </div>
            <div class="col">
                <a class="btn btn-light float-end" asp-action="Index">All</a>
            </div>
        </div>
    </div>
    <div class="col-md-8 offset-2">
        <table class="table">
            <thead>
                <tr class="text-center">
                    <th>@Html.DisplayNameFor(model => model.First().IsbnNumber)</th>
                    <th>@Html.DisplayNameFor(model => model.First().bookStatus)</th>
                    <th>@Html.DisplayNameFor(model => model.First().bookAvailability)</th>
                    <th>@Html.DisplayNameFor(model => model.First().Book)</th>
                    @if (User.Identity.IsAuthenticated && (User.IsInRole("Admin") || User.IsInRole("Librarian")))
                    {
                        <th>Actions</th>
                    }
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <!--
                        <td class="text-center">
                            <img class="rounded-circle" src="item.ProfilePicture" alt="item.FullName" style="max-width: 150px" />
                        </td>-->
                        <td class="align-middle text-center">@Html.DisplayFor(modelItem => item.IsbnNumber)</td>
                        <td class="align-middle text-center">@Html.DisplayFor(modelItem => item.bookStatus)</td>
                        <td class="align-middle text-center">@Html.DisplayFor(modelItem => item.bookAvailability)</td>
                        <td class="align-middle text-center">@Html.DisplayFor(modelItem => item.Book!.Title)</td>
                        @if (User.Identity.IsAuthenticated && (User.IsInRole("Admin") || User.IsInRole("Librarian")))
                        {
                            <td class="align-middle text-center">
                                <a class="btn btn-outline-primary me-2" asp-action="Details" asp-route-id="@item.Id"><i class="bi bi-info-circle"></i> Info</a>
                                @if(item.bookAvailability != BookAvailability.Borrowed)
                                {
                                    <a class="btn btn-light me-2" asp-action="Edit" asp-route-id="@item.Id"><i class="bi bi-pencil-square"></i> Edit</a>
                                    @if (User.Identity.IsAuthenticated && User.IsInRole("Admin"))
                                    {
                                        <a class="btn btn-outline-danger" asp-action="Delete" asp-route-id="@item.Id"><i class="bi bi-trash"></i> Delete</a>
                                    }
                                }
                            </td>
                        }
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>

@if (User.Identity.IsAuthenticated && (User.IsInRole("Admin") || User.IsInRole("Librarian")))
{
    @await Html.PartialAsync("_CreateItem", "BookInstance")
}

<partial name="_Pager" view-data="viewData"/>

@section scripts
{
    <script>
        $(document).ready(function () {
            $("#searchedString").autocomplete({
                source: function (request, response) {
                    $.ajax({
                        url: "/Book/GetTitle",
                        type: "POST",
                        dataType: "json",
                        data: { term: request.term },
                        success: function (data) {
                            response($.map(data, function (item) {
                                return { label: item.name, value: item.name };
                            }));
                        }
                    });
                },
                minLength: 3
            });
        });
    </script>
}